### ISSUE TITLE
post title

### ISSUE THREAD

**Issue by feng19** [elpikel/cmd_arek#4]
Hi, I have benefited a lot from your articles, thank you.

But, I found each post's title always are "Using LiveView and Genservers to track BTC price":

https://github.com/elpikel/cmd_arek/blob/master/pages/api-token-cache.html#L6
https://github.com/elpikel/cmd_arek/blob/master/pages/generate-pdfs-in-elixir.html#L6
https://github.com/elpikel/cmd_arek/blob/master/pages/generate-thumbnails-in-elixir.html#L6

**Comment by elpikel** [comment]
I'm glad to hear that. I fixed titles and added some structure to headers - ea2ef3d. Thank you.

**Comment by feng19** [comment]
👍
